apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: nginx
    host: toctoc-shell
  name: nginx
  selfLink: /api/v1/namespaces/default/services/nginx
  annotations:
    
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-east-1:573624488707:certificate/4fb1a4ae-ce9c-462a-8c9e-020f86323292
    
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: 443
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx
    host: toctoc-shell
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}