apiVersion: apps/v1 # Usa apps/v1beta2 para versiones anteriores a 1.9.0
kind: Deployment
metadata:
  name: procesamiento
  labels:
    app: procesamiento
    host: toctoc-shell
spec:
  selector:
    matchLabels:
      app: procesamiento
  replicas: 1 # indica al controlador que ejecute 2 pods
  template:
    metadata:
      labels:
        app: procesamiento
        host: toctoc-shell
    spec:
      containers:
      - name: procesamiento
        image: 573624488707.dkr.ecr.us-east-1.amazonaws.com/procesamiento:latest
      nodeSelector:
        host: toctoc-shell
