apiVersion: apps/v1 # Usa apps/v1beta2 para versiones anteriores a 1.9.0
kind: Deployment
metadata:
  name: toctoc-usado
  labels:
    app: toctoc-usado
    host: toctoc-shell
spec:
  selector:
    matchLabels:
      app: toctoc-usado
  replicas: 2 # indica al controlador que ejecute 2 pods
  template:
    metadata:
      labels:
        app: toctoc-usado
        host: toctoc-shell
    spec:
      containers:
      - name: toctoc-usado
        image: 573624488707.dkr.ecr.us-east-1.amazonaws.com/toctoc-usado:latest
      nodeSelector:
        host: toctoc-shell
