apiVersion: apps/v1 # Usa apps/v1beta2 para versiones anteriores a 1.9.0
kind: Deployment
metadata:
  name: toctoc-nuevo
  labels:
    app: toctoc-nuevo
    host: toctoc-shell
spec:
  selector:
    matchLabels:
      app: toctoc-nuevo
  replicas: 1 # indica al controlador que ejecute 2 pods
  template:
    metadata:
      labels:
        app: toctoc-nuevo
        host: toctoc-shell
    spec:
      containers:
      - name: toctoc-nuevo
        image: 573624488707.dkr.ecr.us-east-1.amazonaws.com/toctoc-nuevo:latest
      nodeSelector:
        host: toctoc-shell
