apiVersion: apps/v1 # Usa apps/v1beta2 para versiones anteriores a 1.9.0
kind: Deployment
metadata:
  name: urban-server
  labels:
    app: urban-server
    host: toctoc-shell
spec:
  selector:
    matchLabels:
      app: urban-server
  replicas: 1 # indica al controlador que ejecute 2 pods
  template:
    metadata:
      labels:
        app: urban-server
        host: toctoc-shell
    spec:
      containers:
      - name: urban-server
        image: 573624488707.dkr.ecr.us-east-1.amazonaws.com/urban-server:latest
      nodeSelector:
        host: toctoc-shell
