apiVersion: apps/v1 # Usa apps/v1beta2 para versiones anteriores a 1.9.0
kind: Deployment
metadata:
  name: toctoc-login
  labels:
    app: toctoc-login
    host: toctoc-shell
spec:
  selector:
    matchLabels:
      app: toctoc-login
  replicas: 1 # indica al controlador que ejecute 2 pods
  template:
    metadata:
      labels:
        app: toctoc-login
        host: toctoc-shell
    spec:
      containers:
      - name: toctoc-login
        image: 573624488707.dkr.ecr.us-east-1.amazonaws.com/toctoc-login:latest
      nodeSelector:
        host: toctoc-shell
