apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: correobienvenida
  namespace: default
spec:
  schedule: "*/60 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: cron-correo-bienvenida
            image: buildpack-deps:curl
            imagePullPolicy: IfNotPresent
            args:
            - /bin/sh
            - -ec
            - date; curl http://portal-corredoras:3000/gestioncorredor/api/correo-bienvenida
          restartPolicy: OnFailure
          terminationGracePeriodSeconds: 0
  
  concurrencyPolicy: Forbid