apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: carritoabandonado
  namespace: default
spec:
  schedule: "* */24 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: cron-carrito-abandonado
            image: buildpack-deps:curl
            imagePullPolicy: IfNotPresent
            args:
            - /bin/sh
            - -ec
            - date; curl http://portal-corredoras:3000/gestioncorredor/api/carrito-abandonado
          restartPolicy: OnFailure
          terminationGracePeriodSeconds: 0
  
  concurrencyPolicy: Forbid